[package]
name = "legion_ui"
version.workspace = true
edition.workspace = true

[dependencies]
legion_terminal = { path = "../legion_terminal" }

gpui.workspace = true
anyhow.workspace = true
tracing.workspace = true
